name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - name: 🦑 Achievements
        uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_display: large
          plugin_languages: yes
          plugin_achievements: yes
          plugin_languages_aliases: javascript:JS typescript:TS
          plugin_achievements_display: compact

      - name: 🦑 General
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_notable: yes
          plugin_notable_repositories: yes
          plugin_discussions: yes
          
      - name: Indepth analysis 
        uses: lowlighter/metrics@latest
        with:
          filename: activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_habits: yes
          plugin_habits_facts: yes     
          plugin_habits_charts: yes     
          plugin_habits_trim: yes 

          plugin_achievements_only: >-
              polyglot, stargazer, sponsor, deployer, Contributor, maintainer, developer,
              scripter, packager, explorer
          plugin_achievements_display: compact
          plugin_achievements_threshold: X


