name: "📅 Isometric commit calendar"
category: github
index: 0
supports:
  - user
inputs:

  plugin_isocalendar:
    description: Display an isometric view of your commits calendar
    type: boolean
    default: no

  plugin_isocalendar_duration:
    description: Set time window shown by isometric calendar
    type: string
    default: half-year
    values:
      - half-year
      - full-year
